#+TITLE: Outline of Changes 
#+SUBTITLE: Second Edition of "Displaying Time Series, Spatial, and Space-Time Data with R"
#+AUTHOR: Oscar Perpiñán Lamigueiro
#+DATE: November 2017
#+OPTIONS: toc:nil num:nil
#+LATEX_HEADER: \usepackage{mathpazo}
#+LATEX_HEADER: \usepackage[usenames,svgnames,dvipsnames]{xcolor}
#+LATEX_HEADER: \hypersetup{colorlinks=true, linkcolor=Blue, urlcolor=Blue}


* Time Series

- Code have been revised, cleaned and improved. Bugs have been fixed. 

- After data creation or transformation, a text frame with the output of =summary()= has been included.

- Code using =base::reshape= has been replaced by =reshape2::melt= and =reshape2::dcast=.

** Time on the Horizontal Axis

- Alternative code based on =ggplot2= for the Figure 3.9 (/Level plot of differences between a daily temperature time .../).

- New "Interactive Graphics" section (Section 3.4):
  - Some figures have an interactive alternative with code based on the packages =dygraphs=, =highcharter=, =plotly=, and =streamgraph=.
  - The =gridSVG= section has been revised and moved here (Section 3.4.4).
  - This section includes snapshots of the interactive graphics that will be available in the updated webpage.
  
** Time as a Conditioning or Grouping Variable

- Alternative code based on =ggplot2= (using package =GGally=) for the Figure 4.1 (/Scatter plot matrix of the collection.../).

** Time as a Complementary Variable

- New "Interactive Graphics: animation" section (Section 5.6):
  - A new section based on the package =plotly= has been created (section 5.6.1).
  - Original sections using =googleVis= and =gridSVG= have been revised and moved here.
  - This section includes snapshots of the interactive graphics that will be available in the updated webpage.

** About the Data
- Data URLs have been checked and updated where needed.
 
* Spatial Data

To Do.
* Space-Time Data
To Do.
