* Interactive graphics

In the last two years several R packages devoted to interactive graphics have been published. The =htmlwidgets= package is the framework for creating R bindings to popular JavaScript libraries. In the context of the book these are the more interesting packages:

- =leaflet= (spatial data): https://rstudio.github.io/leaflet/ ("Leaflet is a JavaScript library for creating dynamic maps that support panning and zooming along with various annotations like markers, polygons, and popups.")
- =mapview= (spatial data): http://environmentalinformatics-marburg.github.io/mapview/introduction.html ("mapview was created o fill the gap of quick (not presentation grade) interactive plotting to examine and visually investigate spatial data")
- =dygraphs= (time series): http://rstudio.github.io/dygraphs/ ("Dygraphs provides rich facilities for charting time-series data in R and includes support for many interactive features including series/point highlighting, zooming, and panning.")
- =highcharter= (time series and maps): http://jkunst.com/highcharter/
- =rglwidget=: http://www.htmlwidgets.org/showcase_rglwidget.html

Most of the examples of interactive graphics included in the book make use of the =gridSVG= package. Unfortunately this package is not of common usage nowadays and their authors are not adding new features to it. Therefore, I will rewrite these examples with the new packages.

* New features in the =sp= package
The =sp= package includes in its version 1.2.0 new features that should be covered in the book:
- A new function =panel.ggmap=: The Air Madrid example will be modified to use it.
- A new class SpatialMultipoints (an unique feature can be represented with multiple locations): A new example will be included to display this kind of objects.

On the other hand, Edzer Pebesma has recently published the =sf= package, implementing Simple Features for R (https://cran.r-project.org/package=sf). The visualization methods included in this package are still in development, but I think it is interesting to devote an example to this package.

* Bug fixes, and improvements

- Make animated plots code from Chapter 13 portable
- Improve figure 3.9 (calendar plot)
https://mvuorre.github.io/post/2016/2016-03-24-github-waffle-plot/
https://github.com/hrbrmstr/waffle
- Bivariate Choropleth Maps: A How-to Guide
http://www.joshuastevens.net/cartography/make-a-bivariate-choropleth-map/
