#+PROPERTY:  header-args :session *R* :tangle ../docs/R/cartogram.R :eval no-export
#+OPTIONS: ^:nil

#+begin_src R :exports none :tangle no
Sys.setlocale("LC_TIME", 'C')

setwd("~/github/bookvis/")
#+end_src

#+begin_src R :exports none  
##################################################################
## Initial configuration
##################################################################
## Clone or download the repository and set the working directory
## with setwd to the folder where the repository is located.

##################################################################
#+end_src

* Introduction

The graphics in this chapter display the gross domestic product (GDP)
and population of each province in Spain with three different types of
cartograms.

The package =cartogram= implements this type of visual
representations. It is based on =sf=. Thus, the graphics in this
chapter will be produced with =ggplot2=:

#+INDEX: Packages!sf@\texttt{sf}
#+INDEX: Packages!cartogram@\texttt{cartogram}

#+begin_src R
library("ggplot2")
library("sf")
library("cartogram")
#+end_src

* Data

The data is available in the shapefile =sfPopGDPSpain= (read Chapter
ref:cha:dataSpatial for details). Figure
ref:fig:scatterplotPopGDPSpain contains three scatterplots: GDP for
each province, population for each province, and GDP versus
population. It is clear that two provinces, Madrid and Barcelona, have
a population and a GDP significantly higher than the rest. Besides,
the relation between these variables is approximately linear.

#+begin_src R
sfPopGDPSpain <- st_read("data/Spatial/sfPopGDPSpain.shp")
#+end_src

#+begin_src R :results output graphics file :exports both :file figs/Spatial/PopSpain.pdf
ggplot(sfPopGDPSpain) +
  geom_point(aes(y = Province, x = Population/1e6)) +
  xlab("Population (million)") + 
  theme_bw()
#+end_src


#+begin_src R :results output graphics file :exports both :file figs/Spatial/GDPSpain.pdf
ggplot(sfPopGDPSpain) +
  geom_point(aes(y = Province, x = GDP/1e6)) +
  xlab("GDP (million euros)") + 
  theme_bw()
#+end_src


#+begin_src R :results output graphics file :exports both :file figs/Spatial/PopGDPSpain.pdf
ggplot(sfPopGDPSpain, aes(y = Population/1e6, x = GDP/1e6)) +
  geom_point() +
  geom_smooth() + 
  xlab("GDP (million euros)") + ylab("Population (million)") +
  theme_bw()
#+end_src

#+begin_export latex
\begin{figure}
  \begin{minipage}{0.33\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/PopSpain.pdf}
    \end{center}
    \subcaption{Population}
    \label{fig:popSpain}
  \end{minipage}
  \begin{minipage}{0.33\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/GDPSpain.pdf}
    \end{center}
    \subcaption{GDP}
    \label{fig:GDPSpain}
  \end{minipage}
  \begin{minipage}{0.33\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/PopGDPSpain.pdf}
    \end{center}
    \subcaption{GDP vs Population.}
    \label{fig:PopGDPSpain}
  \end{minipage}
  \caption{Population and GDP of the provinces in Spain (2020)} \label{fig:scatterplotPopGDPSpain}
\end{figure}
#+end_export

* Cartograms

The first method is the non-contiguous area cartogram. This solution
enlarges or reduces each polygon in size according to the variable
while preserving its shape.

The function =cartogram_ncont= computes the transformation based on
the variable identified by the argument =weight=, and returns a =sf=
object. The result is displayed with =geom_sf= (Figure
ref:fig:cartNContPopGDPSpain).

#+begin_src R :results output graphics file :exports both :file figs/Spatial/cartNContPopSpain.pdf
cartPopNCont <- cartogram_ncont(sfPopGDPSpain, weight = "Population")

ggplot(cartPopNCont) +
  geom_sf(aes(fill = Population)) + 
  scale_fill_distiller(palette = "Blues", direction = 1) + 
  theme_bw()
#+end_src

#+begin_src R :results output graphics file :exports both :file figs/Spatial/cartNContGDPSpain.pdf
cartGDPNCont <- cartogram_ncont(sfPopGDPSpain, weight = "GDP")

ggplot(cartGDPNCont) +
  geom_sf(aes(fill = GDP)) + 
  scale_fill_distiller(palette = "Blues", direction = 1) + 
  theme_bw()
#+end_src

#+begin_export latex
\begin{figure}
  \begin{minipage}{0.4\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/cartNContPopSpain.pdf}
    \end{center}
    \subcaption{Population}
    \label{fig:cartNContPopSpain}
  \end{minipage}
  \begin{minipage}{0.4\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/cartNContGDPSpain.pdf}
    \end{center}
    \subcaption{GDP}
    \label{fig:cartNContGDPSpain}
  \end{minipage}
  \caption{Non-contiguous cartograms of population and GDP of the provinces in Spain (2020)} \label{fig:cartNContPopGDPSpain}
\end{figure}
#+end_export

The second type is the continuous area cartogram. The polygon of each
province is both scaled and distorted so that its area is directly
proportional to the variable being represented while maintaining
adjacent edges.

The =sf= objects produced by the function =cartogram_cont= are
displayed in Figure ref:fig:cartContPopGDPSpain.

#+begin_src R :results output graphics file :exports both :file figs/Spatial/cartContPopSpain.pdf
cartPopCont <- cartogram_cont(sfPopGDPSpain,
                              weight = "Population")

ggplot(cartPopCont) +
  geom_sf(aes(fill = Population)) + 
  scale_fill_distiller(palette = "Blues", direction = 1) + 
  theme_bw()
#+end_src

#+begin_src R :results output graphics file :exports both :file figs/Spatial/cartContGDPSpain.pdf
cartGDPCont <- cartogram_cont(sfPopGDPSpain,
                              weight = "GDP")

ggplot(cartPopCont) +
  geom_sf(aes(fill = GDP)) + 
  scale_fill_distiller(palette = "Blues", direction = 1) + 
  theme_bw()
#+end_src

#+begin_export latex
\begin{figure}
  \begin{minipage}{0.4\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/cartContPopSpain.pdf}
    \end{center}
    \subcaption{Population}
    \label{fig:cartContpopSpain}
  \end{minipage}
  \begin{minipage}{0.4\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/cartContGDPSpain.pdf}
    \end{center}
    \subcaption{GDP}
    \label{fig:cartContGDPSpain}
  \end{minipage}
  \caption{Contiguous cartograms of population and GDP of the provinces in Spain (2020)}
  \label{fig:cartContPopGDPSpain}
\end{figure}
#+end_export


Finally, the third method is the Dorling cartogram. Provinces are
represented by non-overlapping circles, sized proportionally to the
data, resembling proportional symbol maps (Chapter ref:cha:bubble).

The function =cartogram_dorling= creates the circles, and the result
is represented in Figure ref:fig:cartDorlPopGDPSpain.

#+begin_src R :results output graphics file :exports both :file figs/Spatial/cartDorlPopSpain.pdf
cartPopDorl <- cartogram_dorling(sfPopGDPSpain, weight = "Population")

ggplot(cartPopDorl) +
  geom_sf(aes(fill = Population)) + 
  scale_fill_distiller(palette = "Blues", direction = 1) + 
  theme_bw()
#+end_src

#+begin_src R :results output graphics file :exports both :file figs/Spatial/cartDorlGDPSpain.pdf
cartGDPDorl <- cartogram_dorling(sfPopGDPSpain, weight = "GDP")

ggplot(cartGDPDorl) +
  geom_sf(aes(fill = GDP)) + 
  scale_fill_distiller(palette = "Blues", direction = 1) + 
  theme_bw()
#+end_src

#+begin_export latex
\begin{figure}
  \begin{minipage}{0.4\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/cartDorlPopSpain.pdf}
    \end{center}
    \subcaption{Population}
    \label{fig:cartDorlpopSpain}
  \end{minipage}
  \begin{minipage}{0.4\textheight}
    \begin{center}
      \includegraphics[width=\textwidth]{figs/Spatial/cartDorlGDPSpain.pdf}
    \end{center}
    \subcaption{GDP}
    \label{fig:cartDorlGDPSpain}
  \end{minipage}
  \caption{Non-overlapping circles cartograms of population and GDP of the provinces in Spain (2020).}
  \label{fig:cartDorlPopGDPSpain}
\end{figure}
#+end_export

* COMMENT Local Variables
Local Variables:
ispell-local-dictionary: "british"
End:
