#+PROPERTY:  header-args :session *R* :tangle ../docs/R/vector.R :eval no-export
#+OPTIONS: ^:nil

#+begin_src R :exports none :tangle no
setwd('~/github/bookvis/')
#+end_src

#+begin_src R :exports none  
##################################################################
## Initial configuration
##################################################################
## Clone or download the repository and set the working directory
## with setwd to the folder where the repository is located.
#+end_src

* Introduction

The graphics of this chapter display the vector fields defined by the
wind direction and speed forecast published in the THREDSS
server[fn:1] of Meteogalicia[fn:2]. This server provides access
through different protocols to the output of a Weather Research and
Forecasting (WRF) model, a mesoscale numerical weather prediction
system.

\nomenclature{WRF}{Weather Research and Forecasting model.}

This vector field is encoded in a =RasterStack= object with two
layers: wind speed or vector magnitude, and wind direction or vector
direction.

#+INDEX: Packages!rasterVis@\texttt{rasterVis}
#+INDEX: Packages!raster@\texttt{raster}
#+INDEX: Packages!RColorBrewer@\texttt{RColorBrewer}
#+INDEX: Data!Wind speed
#+INDEX: Data!MeteoGalicia

#+begin_src R 
library("raster")
library("rasterVis")
library("RColorBrewer")

## Local vector direction 
wDir <- raster('data/Spatial/wDir')/180*pi
## Local vector magnitude
wSpeed <- raster('data/Spatial/wSpeed')
## Vector field encoded in a RasterStack with two layers, magnitude
## and direction
windField <- stack(wSpeed, wDir)
names(windField) <- c('magnitude', 'direction')
#+end_src

* Arrow Plot
label:sec:vectorplot
#+begin_src R :exports none
##################################################################
## Arrow plot
##################################################################
#+end_src
A frequent vector visualization technique is the arrow plot, which
draws a small arrow at discrete points within the vector field
(Figure ref:fig:vectorplot). This approach is best suited for
small datasets. If the grid of discrete points gets too dense or
if the variations in magnitude are too big, the images tend to be
visually confusing.

The =rasterVis= package includes the function =vectorplot=, based on
=lattice=[fn:3]. This function is able to display vector fields computed
from a =Raster= object. Moreover, as the next example illustrates,
this function displays =RasterStack= and =RasterBrick= objects with
two layers encoding a vector field, slope (local vector magnitude) and
aspect (local vector direction).

#+begin_src R :results output graphics file :exports both :file figs/Spatial/vectorplot.pdf
vectorTheme <- BTCTheme(regions = list(alpha = 0.7))

vectorplot(windField,
           isField = TRUE, ##RasterStack is a vector field
           aspX = 5, aspY = 5, ##Multipliers to adjust the relation
                               ##between slope/aspect and
                               ##horizontal/vertical displacements in
                               ##the figure.
           scaleSlope = FALSE, ## Slope values are *not* scaled
           par.settings = vectorTheme, 
           colorkey = FALSE,
           scales = list(draw = FALSE))
#+end_src

#+CAPTION: Arrow plot of the wind vector field. label:fig:vectorplot
#+RESULTS:
[[file:figs/Spatial/vectorplot.pdf]]

* Streamlines
#+begin_src R :exports none
##################################################################
## Streamlines
##################################################################
#+end_src

Another solution is to depict the directional structure of the vector
field by its integral curves, also denoted as flow lines or
streamlines. There are a variety of algorithms to produce such
visualization. The =streamplot= function of =rasterVis= displays
streamlines with a procedure inspired by the FROLIC algorithm
cite:Wegenkittl.Groeller1997: For each point, /droplet/, of a jittered
regular grid, a short streamline portion, /streamlet/, is calculated
by integrating the underlying vector field at that point. The main
color of each streamlet indicates local vector magnitude. Streamlets
are composed of points whose sizes, positions, and color degradation
encode the local vector direction (Figure ref:fig:streamplot).

#+INDEX: Subjects!Sequential palette

#+begin_src R :results output graphics file :exports both :file figs/Spatial/streamplot.pdf
myTheme <- streamTheme(
    region = rev(brewer.pal(n = 4, "Greys")),
    symbol = rev(brewer.pal(n = 9, "Blues")))

streamplot(windField, isField = TRUE,
           par.settings = myTheme,
           droplet = list(pc = 12), ## Amount of droplets, percentage of cells
           streamlet = list(L = 5, ## Length of the streamlet
                            h = 5), ## Calculation step
           scales = list(draw = FALSE),
           panel = panel.levelplot.raster)
#+end_src

#+CAPTION: Streamlines of the wind vector field. label:fig:streamplot
#+RESULTS:
[[file:figs/Spatial/streamplot.pdf]]

The magic of Figures ref:fig:vectorplot and ref:fig:streamplot is that
they show the underlying physical structure of the spatial region only
displaying wind speed and direction. It is easy to recognize the
Iberian Peninsula surrounded by strong winds along the eastern and
northern coasts. Another feature easily distinguishable is the Strait
of Gibraltar, a channel that connects the Atlantic Ocean to the
Mediterranean Sea between the south of Spain and the north of
Morocco. Also apparent are the Pyrenees mountains and some of the
river valleys.

* Footnotes

[fn:3] A =ggplot2= solution is available in the =ggquiver= package (https://github.com/mitchelloharawild/ggquiver), although it does not understand =Raster= objects.


[fn:1] http://mandeo.meteogalicia.es/thredds/catalogos/WRF_2D/catalog.html

[fn:2] http://www.meteogalicia.es



* COMMENT Local Variables
Local Variables:
ispell-local-dictionary: "british"
End:
