(TeX-add-style-hook "timeComplementary"
 (lambda ()
    (LaTeX-add-index-entries
     "CO2@$CO_2$"
     "World Bank"
     "Packages!googleVis@\\texttt{googleVis}"
     "Packages!RColorBrewer@\\texttt{RColorBrewer}"
     "brewer.pal@\\texttt{brewer.pal}"
     "aggregate@\\texttt{aggregate}"
     "hclust@\\texttt{hclust}"
     "simpleTheme@\\texttt{simpleTheme}"
     "panel.text@\\texttt{panel.text}"
     "subscripts@\\texttt{subscripts}"
     "Panel function"
     "panel.superpose@\\texttt{panel.superpose}"
     "Packages!latticeExtra@\\texttt{latticeExtra}"
     "glayer@\\texttt{glayer}"
     "+.trellis@\\texttt{+.trellis}"
     "group.value@\\texttt{group.value}"
     "group.number@\\texttt{group.number}"
     "Packages!directlabels@\\texttt{directlabels}"
     "direct.label@\\texttt{direct.label}"
     "Packages!classInt@\\texttt{classInt}"
     "classIntervals@\\texttt{classIntervals}"
     "Packages!gridSVG@\\texttt{gridSVG}"
     "animUnit\\texttt{animUnit}"
     "grid.animate@\\texttt{grid.animate}"
     "grid.hyperlink@\\texttt{grid.hyperlink}"
     "gridToSVG@\\texttt{gridToSVG}")
    (LaTeX-add-labels
     "sec-1"
     "fig:googleVis"
     "fig:CO2-GNI"
     "sec-2"
     "fig:hclustCO2"
     "sec-3"
     "sec-4"
     "fig:CO2-GNI-glayer"
     "fig:CO2-GNI-DL"
     "sec-5"
     "fig:CO2-GNI-panel"
     "fig:CO2-GNI-panel-labels"
     "sec-5-1"
     "fig:CO2pointsGG"
     "fig:CO2points"
     "sec-6"
     "fig:bubblesSVG")))

