(TeX-add-style-hook "timeHorizontalAxis"
 (lambda ()
    (LaTeX-add-index-entries
     "Panel function"
     "panel.xblocks@\\texttt{panel.xblocks}"
     "panel.text@\\texttt{panel.text}"
     "panel.number@\\texttt{panel.number}"
     "panel.points@\\texttt{panel.points}"
     "zoo@\\texttt{zoo}"
     "xyplot.zoo@\\texttt{xyplot.zoo}"
     "Horizon graph"
     "Small multiples"
     "Packages!latticeExtra@\\texttt{latticeExtra}"
     "horizonplot@\\texttt{horizonplot}"
     "Packages!gridSVG@\\texttt{gridSVG}"
     "grid.ls@\\texttt{grid.ls}"
     "grid.garnish@\\texttt{grid.garnish}"
     "grid.script@\\texttt{grid.script}"
     "Javascript"
     "gridToSVG@\\texttt{gridToSVG}"
     "superpose.polygon@\\texttt{superpose.polygon}"
     "trellis.par.get@\\texttt{trellis.par.get}"
     "apply@\\texttt{apply}"
     "sapply@\\texttt{sapply}"
     "unstack@\\texttt{unstack}"
     "panel.polygon@\\texttt{panel.polygon}")
    (LaTeX-add-labels
     "sec-1"
     "sec:differentVariables"
     "fig:aranjuezNaive"
     "fig:aranjuezNaiveGG"
     "sec-1-1"
     "fig:aranjuezEnhanced"
     "sec-2"
     "SEC:sameScale"
     "fig:navarraNaive"
     "sec-2-1"
     "fig:navarraBanking"
     "sec-2-2"
     "fig:navarraHorizonplot"
     "sec-2-3"
     "fig:diffTa_xyplot"
     "fig:diffTa_horizon"
     "fig:diffTa_level"
     "sec-2-4"
     "fig:navarraSVG"
     "sec-3"
     "fig:unemployUSAxyplot"
     "fig:unemployUSAgeomArea"
     "fig:unemployUSAThemeRiver"
     "sec-3-1"
     "sec:themeRiverPanel"
     "fig:themeRiverError")))

